export const GET_USER = "GET_USER";

export const FILL_CARDS_STATE = 'FILL_CARDS_STATE';
export const FLIP_CARD = 'FLIP_CARD';
export const CLEAR_GAME_FIELD = 'CLEAR_GAME_FIELD';
export const DECREASE_COUNTER = 'DECREASE_COUNTER';
export const INIT_GAME_PLAY = 'INIT_GAME_PLAY';
export const CLEAR_CSS_CLASSES = 'DELETE_CSS_CLASS';
export const ROTATE_CARDS_BACK = 'ROTATE_CARDS_BACK';
export const DISAPPEAR_CARDS = 'DISAPPEAR_CARDS';
export const BLOCK_ONCLICK = 'BLOCK_ONCLICK';
export const ADD_CARD_TO_DISCOVERED_CARDS = 'ADD_CARD_TO_DISCOVERED_CARDS';
export const CLEAR_DISCOVERED_ARRAY = 'CLEAR_DISCOVERED_ARRAY';
export const TICK = 'TICK';

export const PREPARE_RESULTS_TO_STATE = 'PREPARE_RESULTS_TO_STATE';
export const CLEAR_PREPARED_ARRAY = 'CLEAR_PREPARED_ARRAY';